//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateTheMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluations
    {
        public Evaluations()
        {
            this.Meeting_questions = new HashSet<Meeting_questions>();
        }
    
        public int ID_Evaluation { get; set; }
        public int ID_Meeting { get; set; }
        public int ID_Attender { get; set; }
    
        public virtual Meeting_attenders Meeting_attenders { get; set; }
        public virtual ICollection<Meeting_questions> Meeting_questions { get; set; }
    }
}
