//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateTheMeeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Meeting_questions = new HashSet<Meeting_questions>();
        }
    
        public int ID_Question { get; set; }
        public string Question { get; set; }
    
        public virtual ICollection<Meeting_questions> Meeting_questions { get; set; }
    }
}
